{% set name = "poethepoet" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poethepoet-{{ version }}.tar.gz
  sha256: 86203acce555bbfe45cb6ccac61ba8b16a5784264484195874da457ddabf5850

build:
  noarch: python
  entry_points:
    - poe = poethepoet:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pastel >=0.2.0,<0.3.0
    - tomlkit >=0.6.0,<1.0.0
    - pyyaml
    - tomli

test:
  imports:
    - poethepoet
  commands:
    - pip check
    - poe --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nat-n/poethepoet
  summary: A task runner that works well with poetry.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay
